# Generated by Django 3.2.1 on 2022-02-14 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(default='1hour 30mins', max_length=50)),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField(default=0)),
                ('casts', models.CharField(max_length=500)),
                ('view_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('movies_art', models.ImageField(upload_to='thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='WatchDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('daybooked', models.DateField(blank=True, null=True)),
                ('timebooked', models.CharField(blank=True, max_length=20, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('num_of_tickets', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('decline', 'decline'), ('success', 'success')], max_length=10)),
                ('guest_unique_code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('reference_code', models.CharField(blank=True, max_length=50, null=True)),
                ('guests', models.ManyToManyField(to='movies.Audience')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_time', models.TimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtime', to='movies.movies')),
                ('watch_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.watchday')),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='view_date',
            field=models.ManyToManyField(to='movies.WatchDay'),
        ),
        migrations.AddField(
            model_name='audience',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_audience', to='movies.movies'),
        ),
    ]
