# Generated by Django 4.0.1 on 2022-01-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_ticketbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='daybooked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketbooking',
            name='timebooked',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
