# Generated by Django 4.0.1 on 2022-01-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_ticketbooking_daybooked_ticketbooking_timebooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='reference_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
