# Generated by Django 4.0.1 on 2022-01-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_ticketbooking_reference_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='num_of_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
